AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a vulnerable webserver
Parameters:
  WebServerIngressLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  Subnet:
    Type: String
  DeploymentVPC:
    Type: String

Resources:
  vulnWebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds: 
      - !Ref 'InstanceSecurityGroup'
      ImageId: !Ref 'LatestAmiId'
      SubnetId: !Ref Subnet
  
  webServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref webServerRole
  webServerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement: 
          - Action: 
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      Policies:
        - PolicyName: "root"
          PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - Effect: "Allow"
                Action: 
                  - "s3:GetObject"
                  - "s3:ListObject"
                Resource:
                  - !GetAtt DataBucket.Arn

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable web access via port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: !Ref 'WebServerIngressLocation'
      VpcId: !Ref DeploymentVPC
  DataBucket:
    Type: AWS::S3::Bucket
    Properties: 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true